### ISSUE TITLE
We need a way to save user settings.

### ISSUE THREAD

**Issue by ShellyHerself** [gbMichelle/Vulpes#31]
Simple system to set and retrieve values.
Some settings are global.
Some settings are per user.

Needs to save somewhere in the vulpes folder. Vulpes folder can be found in vulpes/memory/global.hpp profile_path() + vulpes/paths.hpp VULPES_PATH. Feel free to add your own sub folder in there.

I am fine with inputting a string for user so your system doesn't need to handle that part. If you do feel interested, the current profile name can be retrieved from vulpes/memory/global.hpp through active_profile_name()

Unit tests can be done with catch.hpp. When adding it to the project I'd put it in util/

**Comment by BinToss** [comment]
This would include the dedicated server settings as well, correct? Would this location contain the IP blacklist?

**Comment by ShellyHerself** [comment]
I was thinking specifically about user settings here, but this is also important.

I want to make the location of IP-blacklists and -bans be configurable. That way users can have multiple setups without having to struggle with syncing files between folders.

For server settings, I have been thinking about a system where we can include other config files. So you have your base set of config files which you include, and then you can basically overwrite anything that needs to be different for this particular instance.

For client settings, I think we should have a less customizable solution to keep it simple for users who just want to play and to make debugging with people less of a hassle.

**Comment by ShellyHerself** [comment]
Profile names can be different from their profile folder names. Make sure to use saved_game_file_get_path_to_enclosing_directory and split it at the last `\\`
